# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('videogame_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('summary', models.TextField()),
                ('realeased', models.DateField()),
                ('cover', models.ImageField(upload_to=b'')),
                ('duration', models.IntegerField()),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trackVideogames.Genre')),
                ('themes', models.ManyToManyField(to='trackVideogames.Theme')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videogame_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videogame', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trackVideogames.Videogame')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='videogame_review',
            unique_together=set([('videogame', 'user')]),
        ),
    ]
