# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackVideogames', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videogame_review',
            new_name='VideogameReview',
        ),
    ]
