# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackVideogames', '0002_videogamereview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamereview',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
