# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackVideogames', '0003_auto_20180219_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogamereview',
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
