# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackVideogames', '0004_videogamereview_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamereview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, null=True, verbose_name='Rating (stars)'),
        ),
        migrations.AlterField(
            model_name='videogamereview',
            name='time_to_beat',
            field=models.IntegerField(null=True),
        ),
    ]
